### ISSUE TITLE
About relation F1

### ISSUE THREAD

**Issue by hanyueZhangmaker** [princeton-nlp/PURE#15]
Hello, I want to know what's the difference between F1 and task_F1 in run_relation.py, Isn't n_gold always equal to e2e_ngold?

**Comment by a3616001** [comment]
Hi! `n_gold` and `e2e_ngold` can be different. `e2e_ngold` is the number of all gold relations; while `n_gold` is the number of gold relations that are considered as a candidate by the relation model. 
Note that some gold relations won't be considered as a candidate, because the entity model may not extract all entities.

Here is an example.
In one sample, there are two gold relational triples `(e1, r1, e2)`, `(e2, r2, e3)`. Here, `e2e_ngold=2`. If the entity model only correctly extracts entities `e1` and `e2`, we will have `n_gold=1`.

`F1` is computed using `e2e_ngold`; `task_F1` is computed using `n_gold` and it is the F1 score if we evaluate the relation classification task individually.

**Comment by hanyueZhangmaker** [comment]
I got it, thank you
