### ISSUE TITLE
Ace Relation Dataset

### ISSUE THREAD

**Issue by MerrickWang1** [princeton-nlp/PURE#19]
Where can we find the Ace2005 Relation dataset with the "predicted_ner" attribute, as mentioned in the README?

Thanks,

**Comment by a3616001** [comment]
Hi! The `predicted_ner` field is the output from the entity model. You should run the entity model to generate the `.json` file with the `predicted_ner` attribute.
You can also use gold entities as input for the relation model by using `--eval_with_gold`.

For the ACE05 dataset: I am sorry but I won't be able to share the ACE05 dataset due to its license. The dataset is available [here](catalog.ldc.upenn.edu/LDC2006T06) (you may want to check with your lab if you can't download it). Once you get the raw dataset, you can just follow the [instructions](https://github.com/luanyi/DyGIE/tree/master/preprocessing) to process it to get a `.json` file.
