### ISSUE TITLE
Preparing input file

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#25]
For your input file that you used here:

{
    document ID (please make sure doc_key can be used to identify a certain document)
  "doc_key": "CNN_ENG_20030306_083604.6",

   sentences in the document, each sentence is a list of tokens
  "sentences": [
    [...],
    [...],
    ["tens", "of", "thousands", "of", "college", ...],
    ...
  ],

   entities (boundaries and entity type) in each sentence
  "ner": [
    [...],
    [...],
    [[26, 26, "LOC"], [14, 14, "PER"], ...], #the boundary positions are indexed in the document level
    ...,
  ],

   relations (two spans and relation type) in each sentence
  "relations": [
    [...],
    [...],
    [[14, 14, 10, 10, "ORG-AFF"], [14, 14, 12, 13, "ORG-AFF"], ...],
    ...
  ]
}

... how did you do the annotation for relations and NER? Was it done using Inception or Tagtog or another tool? Thank you very much again.

**Comment by a3616001** [comment]
We didn't do the annotation by ourselves. All the datasets that we used are publicly available datasets with annotations.

You should be able to find how they annotated the datasets from their websites: [SciERC](http://nlp.cs.washington.edu/sciIE/), [ACE04](https://catalog.ldc.upenn.edu/LDC2005T09), [ACE05](https://catalog.ldc.upenn.edu/LDC2006T06).
For example, SciERC used the [BRAT](https://brat.nlplab.org/about.html) interface for the annotation according to their [annotation guideline](http://nlp.cs.washington.edu/sciIE/annotation_guideline.pdf).

**Comment by AlanQuille** [comment]
Thanks again, your help has been invaluable.

**Comment by appledora** [comment]
So, do you download the data for example, in original sciERC format and then reformat again automatically internally before training the model? Asking this, because a little confused whether to format my custom dataset like sciERC or your input data format, as shown on the `Readme.md` . Also, sciERC annotates sentence wise , as per this link [`lavis.cs.hs-rm.d`](http://lavis.cs.hs-rm.de/storage/spert/public/datasets/scierc/scierc_train.json) . Does `PURE` handle this internally as well?
