### ISSUE TITLE
About the Approximation relation model

### ISSUE THREAD

**Issue by YeDeming** [princeton-nlp/PURE#3]
Hi Zexuan,

Thanks for releasing the nice code.

I am confused that why the "batch computations" is only appiled on inference. Did you try to use the "batch computations" on the training process?

Best, 
Deming

**Comment by a3616001** [comment]
Hi Deming,

Yes, we have tried to use the batch computations during training. But we found training with batch computations will slightly degrade the final performance (e.g., ~0.8% on SciERC). We think this might be some optimization issue, caused by the increased number of training labels in each batch. So we decided to not use batch computations during training to keep the model performing well.


Best,
Zexuan

**Comment by YeDeming** [comment]
Thanks!
