### ISSUE TITLE
attention mask

### ISSUE THREAD

**Issue by Z-JY-Alex** [princeton-nlp/PURE#40]
I want to ask why the dimension of the attention mask in the relation_approx model is [batch_size, from_seq_length, to_seq_length],
and why is the token of the location information (subject and object) spliced after the sentence is masked?

Line 82 of the code in the models.py file in the relations folder

Thank you.

**Comment by a3616001** [comment]
Hello, thanks for your interest!

> why the dimension of the attention mask in the relation_approx model is [batch_size, from_seq_length, to_seq_length]

This is because in our approximation model, the attention matrix is not symmetric (i.e., markers can attend to normal tokens while normal tokens can't attend to markers). In this case, we have to use a 2D attention matrix to specify each token can attend to which.

> why is the token of the location information (subject and object) spliced after the sentence is masked

It doesn't matter that the marker tokens are added at the end of the sentence or in the middle of the sentence; only positional embeddings specify the token positions. In our implementation of the approximation model, we add all marker tokens at the end of the input sentence.
